### ISSUE TITLE
Week 1st and 2nd: comment

### ISSUE THREAD

**Issue by parvizi** [ShaaficiAli/SEG4910Capstone#1]
The outline, objective and etc are good. You are one week late. You need to :
1-	Acquire requirement and write them in the Wiki
2-	Create your tasks and proceed with them
3-	Add your meeting minutes weekly. It should contain 
  a.	Who are in the meeting
  b.	What issues were discussed
  c.	What decisions did you get

**Comment by knab007** [comment]
We completed and updated the following issues:
1- Acquired requirement and wrote them in the Wiki
2- Created our tasks and proceeded with them
3- Added our meeting minutes.
